### ISSUE TITLE
Fix docker hub isssue for e2e tests

### ISSUE THREAD

**Issue by njogz** [medic/cht-interoperability#102]
The e2e Github action is failing as seen [here](https://github.com/medic/cht-interoperability/actions/runs/5135290908/jobs/9240511325) due to too many requests to Docker Hub. A solution is to use the organisation account which has a higher limit on the amount of requests that can be made.

**Comment by craig-landry** [comment]
@njogz Is this issue resolved now?

**Comment by garethbowen** [comment]
I had a look at this and it looks like we're using Medic's AWS instance for the CHT images but we're still pulling a whole lot of third party images from docker hub. If possible we could publish these to AWS or potentially look at caching the images somehow. Another alternative would be to add some delayed retry so it installs eventually.

**Comment by Phil-Mwago** [comment]
I have a similar issue (see attached); having too many requests though the logs on this PR have expired. [Here](https://github.com/medic/cht-interoperability/pull/111) is the PR with the error in the GH Actions.
![image](https://github.com/medic/cht-interoperability/assets/41321750/be940387-6471-48af-a1e7-c2a71c34660c)

**Comment by andrablaj** [comment]
Fixed via https://github.com/medic/cht-interoperability/pull/133
