### ISSUE TITLE
Blog post on the CHT - OpenMRS efforts in Nepal

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-interoperability#119]
Post will not go down into details on where it is being implemented rather that we have a implemenation between OpenMRS and the CHT based on the FHIR standards.

- [x] [Draft blog](https://docs.google.com/document/d/1jzfJtxahNX4DeBnGOOerxJRNcJejDofQ1iQ2ylk039Y/edit?usp=sharing)
- [x] Review with EA team
- [x] [Publish blog](https://medic.org/stories/tracking-patients-across-points-of-care-interoperability-between-openmrs-and-the-community-health-toolkit/)

**Comment by andrablaj** [comment]
Closing this ticket as moved to `Done` by @Phil-Mwago.
