### ISSUE TITLE
Decouple OpenMRS and CHT Endpoints

### ISSUE THREAD

**Issue by witash** [medic/cht-interoperability#124]
Currently, for interopability with OpenMRS, outbound push must use openmrs endpoints.
and communication with openmrs is synchronous; if openmrs is down or returns errors, the outbound push request will fail.

In the other direction, requests from openmrs require the CHT instance to be up and will fail if its not.

In either direction, allow CHT and OpenMRS to save resources in the FHIR server, which will be forwarded downstream asynchronously.
Note that in both directions, the IDs from the other system need to be updated

**Comment by andrablaj** [comment]
Closing this issue as it was moved to `Done`.
