### ISSUE TITLE
OpenMRS sync with FHIR Server (instead of poll)

### ISSUE THREAD

**Issue by witash** [medic/cht-interoperability#125]
Currently, new resources from OpenMRS are sent to OpenHIM via a polling service that queries for new resources and then send requests to create new resources to OpenHIM

1. Move this code to interop repository
2. send identical queries to OpenMRS and FHIR server
3. compare results; any new resources in openmrs, save to FHIR, and new resources in FHIR save to OpenMRS
4. any resources in both, compare fields and update

**Comment by andrablaj** [comment]
Closing this issue as it was moved to `Done`.
