### ISSUE TITLE
Some containers failing in M-series Mac

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-interoperability#134]
**Important**: This is a public repository. Anyone in the world can see what's posted here. If you are posting screenshots or log files, please **carefully examine them for** the presence of any kind of **protected health information** (PHI). Images or logs containing PHI _must_ be posted in fully-redacted form, with no visible PHI.

**Describe the bug**
Running `./startup.sh init` on the `openmrs-mediator` branch on an M series mac fails with the error below
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**To Reproduce**
1. Running `./startup.sh init` while on the `openmrs-mediator` branch and using an M series Macbook

**Expected behavior**
All containers work as expected

**Logs**
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by andrablaj** [comment]
Closed via #135
