### ISSUE TITLE
allow OpenMRS sync to be configureable

### ISSUE THREAD

**Issue by witash** [medic/cht-interoperability#138]
Merging the openmrs branch back to `main` is currently blocked because the mediator starts the openmrs sync on startup without automatically.

Not all interoperability projects will be OpenMRS, so they should be started based on environment variables or configurable settings.

**Comment by witash** [comment]
OpenHIM supports [polling channels](https://openhim.org/docs/user-guide/polling-channels) which matches what we want to do; if enabled, periodically poll an endpoint in the mediator, which does the sync.

1. move the polling task out of the mediator where it doesn't really belong
2. rename LTFU mediator as the default CHT mediator (already done)
3. add a new OpenMRS mediator (already done)
4. add (back) the sync endpoint for openmrs sync
5. add a polling channel as a default channel for the openmrs mediator with the sync endpoint as a route

then, enabling the OpenMRS mediator means setting up the openmrs url and credentials in environment variables (or manually creating the channel on an existing openhim setup; the mediator uses channel variables which can have defaults), and enabling the openmrs mediator in openhim by installing or enabling the default channel.

**Comment by andrablaj** [comment]
Closed via https://github.com/medic/cht-interoperability/pull/139
