### ISSUE TITLE
Sync period not calculated correctly

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-interoperability#144]
**Describe the bug**
The sync period for OpenMRS is not being calculated correctly [here](https://github.com/medic/cht-interoperability/blob/dfe2107e366672082ca9a8d2dd6f70216b8815fc/mediator/src/controllers/openmrs.ts#L8-L9)

**To Reproduce**
- Startup the project by running the startup [command](https://github.com/medic/cht-interoperability/blob/dfe2107e366672082ca9a8d2dd6f70216b8815fc/startup.sh#L1)
- Trigger OpenMRS sync by clicking the "Manually Trigger" button in the OpenMRS Sync channel
- Check the `lastUpdated` query param sent to FHIR and OpenMRS to see that it is not as [configured](https://github.com/medic/cht-interoperability/blob/dfe2107e366672082ca9a8d2dd6f70216b8815fc/mediator/config/index.ts#L38)

**Expected behavior**
Sync period is calculated as expected

**Comment by andrablaj** [comment]
Closed via https://github.com/medic/cht-interoperability/pull/145

**Comment by andrablaj** [comment]
Closed via https://github.com/medic/cht-interoperability/pull/145
