### ISSUE TITLE
Create subscription resource in FHIR server once follow up request is received

### ISSUE THREAD

**Issue by njogz** [medic/cht-interoperability#26]
This will enable the requesting system to be notified once a follow up request has been done.

**Comment by andrablaj** [comment]
Thanks for the clarifications @njogz! I got to step n. 2 so far. 😅 

> This ensures that the patient is also created in the FHIR database.
How can we check that the patient is created in the FHIR Database? I think sharing the relevant URLs would be very helpful.

**Comment by andrablaj** [comment]
@njogz @samuelimoisili @lorerod I will share here the steps I followed to try to reproduce the flow in this ticket:

1. Run CHT locally in [development mode](https://docs.communityhealthtoolkit.org/contribute/code/core/dev-environment/).
2. Upload the config from [this branch](https://github.com/medic/interoperability/pull/16). 
3. A simple way to verify if the config is loaded correctly is to access a URL like `https://*****.my.local-ip.co/#/contacts/someUUID/report/interop_follow_up` and to retrieve correctly the follow up form.
4. Login as an offline user in CHT.
5. Run OpenHIM locally as instructed in the `README`.
6. Create a patient in CHT. At this step, we should see a `fhir/Patient` resource creation in the Transaction log of Admin Console. `However, I am unable to see that resource creation in the log at this point.`
7. Make a LTFU request via Postman, on `http://localhost:5001/mediator/service-request`. The body should look like this:
```
{ 
    "patient_id": "uuid-of-the-patient-previously-created", 
    "callback_url": "https://interop.free.beeceptor.com/callback" 
}
```
I stopped here as I didn't manage to have the patient creation work properly in step 6.

Any configuration that I might have missed that is not yet documented in this ticket?

**Comment by lorerod** [comment]
@njogz @samuelimoisili 
I'm having the same issue as @andrablaj

1. Run CHT locally in [development mode](https://docs.communityhealthtoolkit.org/contribute/code/core/dev-environment/).
2. Upload the config from [this branch](https://github.com/medic/interoperability/pull/16). 
3. Put the interoperability project up using `26-create-subscription-resource` branch and following the [README](https://github.com/medic/interoperability/blob/main/README.md) 
4. I check the mediator calling `GET http://localhost:5001/mediator/` and got a `200 ok` with body 
```
{
    "status": "success"
}
```
5. Login to my local CHT as an offline user.
6. Create a patient in CHT. 
7. I can't see a `fhir/Patient` resource creation in the Transaction log of Admin Console. This is what I see:

![Captura de pantalla 2023-02-24 a la(s) 16 36 01](https://user-images.githubusercontent.com/21312057/221276364-ac0b6cb0-6131-4750-9b8a-0ea8290fc485.png)

8. I made a LTFU request via Postman, on `http://localhost:5001/mediator/service-request`:
```
{ "patient_id": "c4d3e29f-e908-49ea-82d9-099421eb138a", 
"callback_url": "https://interop.free.beeceptor.com/callback" }
```
And I got `500 Interval Server Error` as response.
9. Checked the Transaction log of Admin Console and I can see this:

![Captura de pantalla 2023-02-24 a la(s) 16 38 28](https://user-images.githubusercontent.com/21312057/221276021-8f2e1154-a5da-4aae-a3bd-036065993be3.png)

Maybe we are missing some configuration in the CHT?
