### ISSUE TITLE
Use Medic's eslint config

### ISSUE THREAD

**Issue by njogz** [medic/cht-interoperability#43]
We should use medic's eslint config which can be found [here](https://github.com/medic/eslint-config). We can install it and then depend on it and override/extend where appropriate. One thing to test is that cht-conf is still able to load the cht-config once this change is done.

**Comment by andrablaj** [comment]
@njogz sent this ticket back to "In Progress" as it needs conflict solving.

**Comment by lorerod** [comment]
Hi @njogz and @andrablaj, What I would do with this issue is a simple test of the LTFU flow locally to make sure nothing is broken. I will wait for the conflicts to be solved, and if this happens before my leave, I can test it locally. If not, please go ahead and test it and merge.
