### ISSUE TITLE
Mediator endpoint to create patient in FHIR server

### ISSUE THREAD

**Issue by njogz** [medic/cht-interoperability#5]
Create an endpoint in the OpenHIM mediator that creates a patient in the FHIR server

**Comment by lorerod** [comment]
Hi @njogz, I'm trying to test this and have some doubts.
I'm trying with a POST on `http://localhost:5001/mediator/patient` with a JSON body containing:`{
    "name": "Lorena"
}`
I'm getting 404 - NOT FOUND. 

Also, I need help finding instructions on how to connect my CHT instance to the mediator. So I can test all the circuits.

**Comment by samuelimoisili** [comment]
The bug fix has been fixed and merged, @lorerod  you can test this feature now.

**Comment by lorerod** [comment]
Done @njogz @samuelimoisili. Tested on [issue](https://github.com/medic/interoperability/issues/17)
