### ISSUE TITLE
Implement E2E test

### ISSUE THREAD

**Issue by lorerod** [medic/cht-interoperability#73]
**Describe the issue**
Currently, the project doesn't count with a set of e2e tests, only unit tests for the mediator.

**Describe the improvement you'd like**
Implement the e2e test for one first scenario: The LTFU flow happy path

**Describe alternatives you've considered**
None.

Tasks:
- [ ] Implement e2e  LTFU flow
- [ ] Add e2e to CI pipeline

**Comment by andrablaj** [comment]
@lorerod closing this issue as it was moved to `Done` in the FG board. Great job!
