### ISSUE TITLE
ERROR: Service 'configurator' failed to build : COPY failed: forbidden path outside the build context: ../cht-config ()

### ISSUE THREAD

**Issue by ronna** [medic/cht-interoperability#81]
**Describe the bug**
When running for the first time I am getting error _ERROR: Service 'configurator' failed to build : COPY failed: forbidden path outside the build context: ../cht-config ()_

**To Reproduce**
clone the https://github.com/medic/cht-interoperability run the  ./startup.sh init command

**Expected behavior**
docker images should be downloaded/build

**Logs**
tux@T430s:~/cht-interoperability$ ./startup.sh init
Building configurator
Step 1/12 : FROM node:16-alpine
 ---> 8cf71856f96e
Step 2/12 : RUN apk add g++ make py3-pip git curl chromium
 ---> Using cache
 ---> 7e485d0b1738
Step 3/12 : WORKDIR /scripts/configurator
 ---> Using cache
 ---> 87580573ba73
Step 4/12 : COPY ./configurator ./
 ---> Using cache
 ---> 219afe8e5e0a
Step 5/12 : RUN npm install
 ---> Using cache
 ---> c60c91ee6603
Step 6/12 : WORKDIR /scripts/cht-config
 ---> Using cache
 ---> 0b59f6545ef1
Step 7/12 : COPY ../cht-config ./
ERROR: Service 'configurator' failed to build : COPY failed: forbidden path outside the build context: ../cht-config ()

**Screenshots**

**Environment**
- Instance: 20.04.6 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64)

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by samuelimoisili** [comment]
Hi @ronna, can you share your steps and screenshots, if possible? I tried replicating the error by following the recommended steps on WSL 20.04.6, but I couldn't replicate your error. 

From the error message, it seems like there's an issue with the build context in the docker-compose.yml, but the current version seems to be pointing to the correct build (context)[https://github.com/medic/cht-interoperability/blob/c404bccc007d37b4cb4e3d1a8bab26d750cb8cfb/docker/docker-compose.mediator.yml#L31].

PS: If it's convenient for you, please share this on the (CHT forum)[https://forum.communityhealthtoolkit.org/] and tag me. Thanks.

**Comment by ronna** [comment]
Hi @samuelimoisili 

The issue has been resolved, I upgraded to compose v2 and that solved the issue
